// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2QyorN4a3Tg7TY9qSmV2SkGHR0E8JPas',
    appId: '1:217730760033:web:94b3ac95b727350a2e9920',
    messagingSenderId: '217730760033',
    projectId: 'my-radio-e395b',
    authDomain: 'my-radio-e395b.firebaseapp.com',
    storageBucket: 'my-radio-e395b.firebasestorage.app',
    measurementId: 'G-8VFCQ0M7QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg5EeGkCSvio0_Lk0Zk0nDrVncFbdIfBk',
    appId: '1:217730760033:android:b4e407174ab1ea292e9920',
    messagingSenderId: '217730760033',
    projectId: 'my-radio-e395b',
    storageBucket: 'my-radio-e395b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcqemFDSeXIPJKkSK4dGiFDPUbsKPeDJ8',
    appId: '1:217730760033:ios:1266d9dc39dc62152e9920',
    messagingSenderId: '217730760033',
    projectId: 'my-radio-e395b',
    storageBucket: 'my-radio-e395b.firebasestorage.app',
    iosBundleId: 'com.example.myMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcqemFDSeXIPJKkSK4dGiFDPUbsKPeDJ8',
    appId: '1:217730760033:ios:1266d9dc39dc62152e9920',
    messagingSenderId: '217730760033',
    projectId: 'my-radio-e395b',
    storageBucket: 'my-radio-e395b.firebasestorage.app',
    iosBundleId: 'com.example.myMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2QyorN4a3Tg7TY9qSmV2SkGHR0E8JPas',
    appId: '1:217730760033:web:e12481356864b45c2e9920',
    messagingSenderId: '217730760033',
    projectId: 'my-radio-e395b',
    authDomain: 'my-radio-e395b.firebaseapp.com',
    storageBucket: 'my-radio-e395b.firebasestorage.app',
    measurementId: 'G-FWNT9YJ5TK',
  );
}
